-- Rest alerts while the app is closed: Web Push, sent by a server at the
-- deadline (6f).
--
-- An installed iOS web app can receive Web Push through its service worker
-- since 16.4, but nothing can schedule a LOCAL notification from a closed
-- page, so the alert has to be SENT by something that is still running when
-- the rest ends. That something is the push-alerts edge function; these are
-- the three tables it needs.
--
-- Nothing here is training data. A subscription is a device's address, an
-- alert is a one-shot reminder, and the config row is a key pair. None of it
-- is read by a view, a chart or an MCP tool, and none of it is append-only:
-- an alert that was cancelled is finished, not history.

-- 1. Where to send.
--
-- One row per device subscription. `endpoint` is the push service's URL for
-- that browser and is unique by construction, so a device that subscribes
-- again (after a reinstall, or a second person signing in on the same phone)
-- replaces its own row rather than adding one. Revocation is a timestamp, not
-- a delete: a 410 from the push service is a fact worth keeping for a day of
-- debugging, and the function sets it as the service role.
create table push_subscriptions (
  id          uuid primary key default gen_random_uuid(),
  user_id     uuid not null default auth.uid() references auth.users (id) on delete cascade,
  endpoint    text not null unique,
  -- The client's P-256 public key and 16-byte auth secret, base64url without
  -- padding: 65 bytes is 87 characters, 16 bytes is 22. The shape is pinned
  -- because the function feeds these straight into ECDH and HKDF; a row that
  -- passes here decodes there.
  p256dh      text not null,
  auth        text not null,
  user_agent  text,
  created_at  timestamptz not null default now(),
  revoked_at  timestamptz,
  constraint push_subscriptions_endpoint_https check (
    endpoint ~ '^https://' and length(endpoint) <= 2048
  ),
  constraint push_subscriptions_p256dh_shape check (p256dh ~ '^[A-Za-z0-9_-]{87}$'),
  constraint push_subscriptions_auth_shape check (auth ~ '^[A-Za-z0-9_-]{22}$'),
  constraint push_subscriptions_user_agent_bounded check (
    user_agent is null or length(user_agent) <= 512
  )
);

comment on table push_subscriptions is
  'Web Push subscriptions, one per device. Written by the push-alerts edge '
  'function (service role) and readable by the owner. revoked_at is set when '
  'the person turns the alert off or the push service says the endpoint is gone.';

alter table push_subscriptions enable row level security;

-- The owner may see, add and revoke their own. No delete: a revoked row is
-- how the function knows not to try that endpoint again.
create policy push_subscriptions_select on push_subscriptions
  for select to authenticated using (user_id = auth.uid());
create policy push_subscriptions_insert on push_subscriptions
  for insert to authenticated with check (user_id = auth.uid());
create policy push_subscriptions_update on push_subscriptions
  for update to authenticated
  using (user_id = auth.uid()) with check (user_id = auth.uid());

-- 2. Who is sending.
--
-- The VAPID key pair (RFC 8292) that signs every push. Generated LAZILY by
-- the function on first use with WebCrypto and stored here, so no secret has
-- to be set by hand and the private key never leaves Supabase. The public
-- half is what the browser is handed at subscribe time; a subscription is
-- bound to it, so this pair must never be regenerated while subscriptions
-- exist. `id = 1` makes it a single row.
--
-- RLS on with NO policies, exactly like mcp_tokens: only the service role
-- reads this table, and the service role bypasses RLS, so it needs none. A
-- policy here would not fix a linter note, it would publish the private key.
create table push_config (
  id                smallint primary key check (id = 1),
  vapid_public_key  text not null,
  vapid_private_jwk jsonb not null,
  created_at        timestamptz not null default now()
);

comment on table push_config is
  'The deployment''s VAPID key pair, generated by the push-alerts function on '
  'first use. Service role only: RLS is on and there are deliberately no policies.';

alter table push_config enable row level security;

-- 3. What to send, and when.
--
-- One row per scheduled alert. `schedule` cancels the user's other open
-- alerts before inserting, so at most one is live per person; `cancel` stamps
-- cancelled_at; the sender re-reads the row at the deadline and sends only if
-- it is still open, then stamps sent_at or error. Readable by the owner so a
-- bug report can say what the server believed; written only by the function.
create table rest_alerts (
  id            uuid primary key default gen_random_uuid(),
  user_id       uuid not null references auth.users (id) on delete cascade,
  fire_at       timestamptz not null,
  -- "Barbell Row set 3": the body of the notification. The same single-line
  -- rule as exercises.name, because it is rendered by the OS outside the app.
  label         text not null,
  created_at    timestamptz not null default now(),
  cancelled_at  timestamptz,
  sent_at       timestamptz,
  -- Why it was not delivered, when it was not: status codes, never an endpoint.
  error         text,
  constraint rest_alerts_label_plain check (
    length(label) between 1 and 120
    and label !~ '[\u0001-\u001f\u007f-\u009f]'
    and label !~ '[\u2028\u2029]'
  ),
  constraint rest_alerts_error_bounded check (error is null or length(error) <= 500)
);

comment on table rest_alerts is
  'One-shot "rest over" push alerts. Written only by the push-alerts edge '
  'function; the owner may read. At most one open alert per user at a time.';

-- The sender's and the canceller's lookup: this user's open alerts.
create index idx_rest_alerts_open on rest_alerts (user_id, fire_at)
  where sent_at is null and cancelled_at is null;

alter table rest_alerts enable row level security;

create policy rest_alerts_select on rest_alerts
  for select to authenticated using (user_id = auth.uid());
